export default {
  name: 'page',
  title: 'Page',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'pageType',
      title: 'Page Type',
      type: 'string',
      options: {
        list: [
          { title: 'Home', value: 'home' },
          { title: 'About', value: 'about' },
          { title: 'Strategy', value: 'strategy' },
          { title: 'Audience', value: 'audience' },
          { title: 'Resource Index', value: 'resource-index' },
          { title: 'Video Index', value: 'video-index' },
          { title: 'FAQ', value: 'faq' },
          { title: 'Contact', value: 'contact' },
          { title: 'Assessment Landing', value: 'assessment' },
          { title: 'General Landing', value: 'landing' },
        ],
      },
    },
    {
      name: 'featuredImage',
      title: 'Featured Image',
      type: 'image',
      options: { hotspot: true },
    },
    {
      name: 'sections',
      title: 'Page Sections',
      type: 'array',
      of: [
        { type: 'heroSection' },
        { type: 'trustMetrics' },
        { type: 'introSection' },
        { type: 'problemCards' },
        { type: 'strategyBenefits' },
        { type: 'imageTextSection' },
        { type: 'videoFeature' },
        { type: 'comparisonTable' },
        { type: 'processSteps' },
        { type: 'audienceCards' },
        { type: 'testimonials' },
        { type: 'resourceGrid' },
        { type: 'faqSection' },
        { type: 'assessmentCta' },
        { type: 'disclosureBlock' },
      ],
    },
    { name: 'seo', title: 'SEO', type: 'seo' },
    { name: 'published', title: 'Published', type: 'boolean', initialValue: true },
  ],
};
